import {useEffect,useMemo,useState} from 'react';
import {useRouter} from 'next/router';

const DURATION=3600,NEGATIVE=.25,LETTERS=['A','B','C','D','E'];
const clean=(s='')=>s.replace(/\s*SBI Clerk 2025 Preliminary Exam Recollected Questions\s*\d*\s*/gi,' ').replace(/\s+/g,' ').trim();

export default function MockAttempt(){
 const router=useRouter();
 const [questions,setQuestions]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[idx,setIdx]=useState(0),[answers,setAnswers]=useState({}),[marked,setMarked]=useState({}),[seconds,setSeconds]=useState(DURATION),[submitted,setSubmitted]=useState(false),[started,setStarted]=useState(false);
 useEffect(()=>{
  if(router.query.id!=='sbi-clerk-2025')return;
  fetch('/pre_mock_data.json?bust=20260906',{cache:'no-store'})
   .then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d?.error||'Mock data could not be loaded');return d})
   .then(d=>{if(!Array.isArray(d)||d.length!==100)throw new Error(`Invalid mock data: expected 100 questions, got ${Array.isArray(d)?d.length:'non-array'}`);setQuestions(d);setLoading(false)})
   .catch(e=>{setError(e.message||'Mock could not be loaded');setLoading(false)})
 },[router.query.id]);
 useEffect(()=>{if(!questions.length||submitted)return;try{const x=JSON.parse(localStorage.getItem('dm_pre_sbi_2025_state')||'null');if(x){if(x.answers)setAnswers(x.answers);if(x.marked)setMarked(x.marked);if(Number.isFinite(x.idx))setIdx(Math.min(x.idx,questions.length-1));if(Number.isFinite(x.seconds))setSeconds(x.seconds);if(x.started)setStarted(true)}}catch(e){}},[questions,submitted]);
 useEffect(()=>{if(!started||submitted||!questions.length)return;const t=setInterval(()=>setSeconds(s=>{if(s<=1){clearInterval(t);setSubmitted(true);return 0}return s-1}),1000);return()=>clearInterval(t)},[started,submitted,questions.length]);
 useEffect(()=>{if(questions.length&&!submitted)localStorage.setItem('dm_pre_sbi_2025_state',JSON.stringify({answers,marked,idx,seconds,started}))},[answers,marked,idx,seconds,started,questions.length,submitted]);
 const q=questions[idx],attempted=Object.keys(answers).length;
 const result=useMemo(()=>{if(!submitted)return null;let correct=0,wrong=0,unattempted=0;questions.forEach(x=>{if(!answers[x.id])unattempted++;else if(answers[x.id]===x.answer)correct++;else wrong++});return{correct,wrong,unattempted,score:correct-wrong*NEGATIVE,accuracy:attempted?correct/attempted*100:0}},[submitted,questions,answers,attempted]);
 const go=n=>{setIdx(Math.max(0,Math.min(questions.length-1,n)));window.scrollTo({top:0,behavior:'smooth'})};
 const submit=()=>{if(!started||submitted)return;if(confirm('Submit the mock? You will see your score and solutions.')){setSubmitted(true);localStorage.removeItem('dm_pre_sbi_2025_state');window.scrollTo(0,0)}};
 const fmt=s=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;
 if(loading)return <div style={S.page}><div style={S.box}><h2>Loading SBI Clerk 2025 Mock…</h2><p style={S.muted}>Please wait.</p></div></div>;
 if(error||!questions.length)return <div style={S.page}><div style={S.box}><h2>Mock could not be loaded.</h2><p style={S.muted}>{error||'No questions were returned.'}</p><a href="/pre-mocks" style={S.back}>← Back to PRE MOCKS</a></div></div>;
 if(!started&&!submitted)return <div style={S.page}><div style={{...S.box,maxWidth:760}}><a href="/pre-mocks" style={S.back}>← PRE MOCKS</a><h1>SBI Clerk 2025 Memory Based Paper</h1><p style={S.muted}>100 questions • 60 minutes • English, Numerical Ability & Reasoning</p><div style={S.info}><b>Marking:</b> +1 correct, −0.25 wrong, 0 unattempted.</div><div style={S.info}><b>Important:</b> Recollected paper. The source PDF answer key is used for scoring; a few items may contain source/key inconsistencies.</div><button onClick={()=>setStarted(true)} style={S.primary}>Start Mock →</button></div></div>;
 if(submitted)return <Result questions={questions} answers={answers} result={result}/>;
 return <div style={S.page}><header style={S.header}><div><b>SBI Clerk 2025</b><span style={S.sub}> Memory Based Prelims Mock</span></div><div style={{display:'flex',alignItems:'center',gap:12}}><span style={{fontWeight:800,color:seconds<300?'#c33':'#17233c'}}>⏱ {fmt(seconds)}</span><button onClick={submit} style={S.submit}>Submit Mock</button></div></header><div style={S.layout}><main style={S.box}><div style={{display:'flex',justifyContent:'space-between',gap:10,alignItems:'center',marginBottom:16}}><span style={S.badge}>{q.section}</span><b>Question {q.id} / 100</b></div><div style={S.q}>{clean(q.q)}</div><div>{q.options.map((op,i)=><button key={i} onClick={()=>setAnswers(a=>({...a,[q.id]:LETTERS[i]}))} style={{...S.option,...(answers[q.id]===LETTERS[i]?S.selected:{})}}><span style={S.letter}>{LETTERS[i]}</span><span>{clean(op)}</span></button>)}</div><div style={{display:'flex',justifyContent:'space-between',marginTop:22,gap:8,flexWrap:'wrap'}}><button onClick={()=>setMarked(m=>({...m,[q.id]:!m[q.id]}))} style={S.secondary}>{marked[q.id]?'★ Marked':'☆ Mark for Review'}</button><div style={{display:'flex',gap:8}}><button disabled={idx===0} onClick={()=>go(idx-1)} style={S.secondary}>← Previous</button><button disabled={idx===questions.length-1} onClick={()=>go(idx+1)} style={S.primary}>Next →</button></div></div></main><aside style={S.side}><div style={{fontWeight:800,marginBottom:10}}>Question Palette</div><div style={{display:'flex',gap:7,flexWrap:'wrap'}}>{questions.map((x,i)=><button key={x.id} onClick={()=>go(i)} style={{...S.pal,...(i===idx?S.current:{}),...(answers[x.id]?S.answered:{}),...(marked[x.id]?S.marked:{})}}>{x.id}</button>)}</div><div style={S.legend}><span>● Answered</span><span>★ Marked</span><span>○ Not visited</span></div><div style={{marginTop:18,fontSize:13,color:'#697386'}}><b>{attempted}</b> answered of 100</div></aside></div></div>;
}
function Result({questions,answers,result}){const [show,setShow]=useState('All');return <div style={S.page}><header style={S.header}><div><b>SBI Clerk 2025</b><span style={S.sub}> Result & Solutions</span></div><a href="/pre-mocks" style={S.back}>PRE MOCKS</a></header><div style={{maxWidth:1100,margin:'20px auto',padding:'0 14px'}}><div style={S.scoreGrid}>{[['Score',result.score.toFixed(2)],['Correct',result.correct],['Wrong',result.wrong],['Unattempted',result.unattempted],['Accuracy',result.accuracy.toFixed(1)+'%']].map(x=><div key={x[0]}><small>{x[0]}</small><strong>{x[1]}</strong></div>)}</div><div style={S.info}>Scoring uses the answer key supplied in the uploaded source PDF. Solutions below are explanations prepared for this mock.</div><div style={{display:'flex',gap:8,flexWrap:'wrap',margin:'18px 0'}}>{['All','Correct','Wrong','Unattempted'].map(x=><button key={x} onClick={()=>setShow(x)} style={show===x?S.primary:S.secondary}>{x}</button>)}</div>{questions.map(q=>{const a=answers[q.id],state=!a?'Unattempted':a===q.answer?'Correct':'Wrong';if(show!=='All'&&show!==state)return null;return <div key={q.id} style={S.review}><div style={{display:'flex',justifyContent:'space-between',gap:10}}><b>Q{q.id} · {q.section}</b><span style={{fontWeight:800}}>{state}</span></div><div style={S.q}>{clean(q.q)}</div><div style={{fontSize:14,color:'#3c4658'}}><b>Your answer:</b> {a||'Not attempted'} &nbsp; <b>Source key:</b> {q.answer}</div><div style={S.solution}><b>Solution:</b> {clean(q.solution)}</div></div>})}</div></div>}
const S={page:{minHeight:'100vh',background:'#f4f7fb',fontFamily:'Arial,sans-serif',color:'#17233c',paddingBottom:40},header:{position:'sticky',top:0,zIndex:5,background:'#fff',borderBottom:'1px solid #e4e9f0',padding:'14px 18px',display:'flex',justifyContent:'space-between',alignItems:'center',gap:10,boxShadow:'0 3px 14px rgba(20,40,70,.06)'},sub:{color:'#6b7483',fontWeight:500},layout:{maxWidth:1200,margin:'18px auto',padding:'0 14px',display:'grid',gridTemplateColumns:'minmax(0,1fr) 310px',gap:16},box:{background:'#fff',borderRadius:18,padding:26,boxShadow:'0 8px 30px rgba(30,55,90,.08)',maxWidth:900,margin:'30px auto'},back:{color:'#315d9b',textDecoration:'none',fontWeight:800},muted:{color:'#697386',lineHeight:1.6},info:{background:'#fff8e7',border:'1px solid #f1d58a',borderRadius:12,padding:13,margin:'12px 0',fontSize:13,lineHeight:1.5},primary:{background:'#315d9b',color:'#fff',border:0,borderRadius:10,padding:'11px 16px',fontWeight:800,cursor:'pointer'},secondary:{background:'#fff',color:'#315d9b',border:'1px solid #cbd5e3',borderRadius:10,padding:'10px 14px',fontWeight:800,cursor:'pointer'},submit:{background:'#c0392b',color:'#fff',border:0,borderRadius:10,padding:'10px 14px',fontWeight:800,cursor:'pointer'},badge:{background:'#edf3ff',color:'#315d9b',padding:'6px 9px',borderRadius:999,fontSize:12,fontWeight:800},q:{fontSize:18,lineHeight:1.65,fontWeight:700,margin:'14px 0 20px'},option:{width:'100%',display:'flex',alignItems:'flex-start',gap:12,textAlign:'left',background:'#fff',border:'1px solid #dce3ec',borderRadius:12,padding:'13px 14px',margin:'9px 0',cursor:'pointer',fontSize:15,lineHeight:1.45},selected:{border:'2px solid #315d9b',background:'#f2f6ff'},letter:{minWidth:27,height:27,borderRadius:'50%',background:'#eef2f7',display:'inline-flex',alignItems:'center',justifyContent:'center',fontWeight:800},side:{background:'#fff',borderRadius:18,padding:18,boxShadow:'0 8px 30px rgba(30,55,90,.08)',height:'fit-content',position:'sticky',top:82},pal:{width:36,height:36,borderRadius:9,border:'1px solid #dce3ec',background:'#fff',fontWeight:700,cursor:'pointer'},current:{outline:'3px solid #b8ccef'},answered:{background:'#eaf5ed',borderColor:'#8ac69a'},marked:{boxShadow:'inset 0 -4px 0 #e2a629'},legend:{display:'grid',gap:6,marginTop:15,fontSize:12,color:'#697386'},scoreGrid:{display:'grid',gridTemplateColumns:'repeat(5,1fr)',gap:10,marginBottom:14},review:{background:'#fff',borderRadius:16,padding:20,margin:'12px 0',boxShadow:'0 5px 20px rgba(30,55,90,.06)'},solution:{background:'#f4f8ff',borderLeft:'4px solid #315d9b',padding:12,marginTop:12,lineHeight:1.6,fontSize:14}};
