import { Pool } from "pg";
let pool;
function getPool(){if(!process.env.DATABASE_URL)throw new Error("DATABASE_URL is not configured");if(!pool)pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:{rejectUnauthorized:false},max:3});return pool;}
function isAdmin(req){return /(?:^|;\s*)dm_admin=1(?:;|$)/.test(req.headers.cookie||"");}
function cleanPhone(v){return String(v||"").replace(/\D/g,"");}
async function ensureTable(){const db=getPool();await db.query(`CREATE TABLE IF NOT EXISTS dm_students (phone TEXT PRIMARY KEY,name TEXT,email TEXT,city TEXT,state TEXT,exam_target TEXT DEFAULT 'IBPS PO',about TEXT,first_login_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),last_login_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);await db.query(`CREATE TABLE IF NOT EXISTS dm_group_messages (id TEXT PRIMARY KEY,phone TEXT,name TEXT,sender TEXT NOT NULL CHECK(sender IN ('student','admin')),message TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);await db.query(`CREATE INDEX IF NOT EXISTS dm_group_messages_date_idx ON dm_group_messages(created_at)`);}
async function studentExists(db,phone){const r=await db.query(`SELECT 1 FROM dm_students WHERE phone=$1 LIMIT 1`,[phone]);return !!r.rowCount;}
export default async function handler(req,res){try{const db=getPool();await ensureTable();const admin=isAdmin(req);
if(req.method==="GET"){if(!admin){const phone=cleanPhone(req.query.phone);if(phone.length!==10||!(await studentExists(db,phone)))return res.status(403).json({error:"Group chat is available for logged-in students"});}const r=await db.query(`SELECT id,phone,name,sender,message,created_at FROM dm_group_messages ORDER BY created_at ASC LIMIT 500`);return res.status(200).json({messages:r.rows});}
if(req.method==="POST"){const message=String(req.body?.message||"").trim().slice(0,2000);if(!message)return res.status(400).json({error:"Message is required"});let phone=cleanPhone(req.body?.phone),name=String(req.body?.name||"Student").trim().slice(0,100),sender=admin?"admin":"student";if(!admin){if(phone.length!==10||!(await studentExists(db,phone)))return res.status(403).json({error:"Group chat is available for logged-in students"});}else{phone="ADMIN";name="Admin";}const id=`group_${Date.now()}_${Math.random().toString(36).slice(2,9)}`;const r=await db.query(`INSERT INTO dm_group_messages(id,phone,name,sender,message) VALUES($1,$2,$3,$4,$5) RETURNING id,phone,name,sender,message,created_at`,[id,phone,name,sender,message]);return res.status(201).json({message:r.rows[0]});}
return res.status(405).json({error:"Method not allowed"});}catch(e){console.error("group chat API error",e);return res.status(503).json({error:"Group chat is unavailable. Please configure DATABASE_URL."});}}