import {useEffect,useRef,useState} from "react";
import Link from "next/link";

const css={page:{minHeight:"100vh",background:"#f5f7fb",fontFamily:"Arial,Helvetica,sans-serif",color:"#172033"},top:{height:64,background:"#40537d",color:"#fff",display:"flex",alignItems:"center",justifyContent:"space-between",padding:"0 20px"},layout:{display:"grid",gridTemplateColumns:"300px 1fr",maxWidth:1200,margin:"0 auto",minHeight:"calc(100vh - 64px)"},side:{background:"#fff",borderRight:"1px solid #d7dee9",padding:16},main:{padding:18},listBtn:{width:"100%",textAlign:"left",background:"#fff",border:"1px solid #d7dee9",borderRadius:10,padding:12,marginBottom:8,cursor:"pointer"},card:{background:"#fff",border:"1px solid #d7dee9",borderRadius:14,overflow:"hidden"},messages:{height:"calc(100vh - 190px)",minHeight:420,overflowY:"auto",padding:18,background:"#f8fafc"},bubble:{maxWidth:"78%",padding:"10px 13px",borderRadius:12,marginBottom:10,lineHeight:1.45,whiteSpace:"pre-wrap"},composer:{display:"flex",gap:10,padding:14,borderTop:"1px solid #e3e7ee"},input:{flex:1,border:"1px solid #cbd3df",borderRadius:10,padding:"11px 13px"},button:{border:0,borderRadius:10,padding:"11px 18px",background:"#3d78c2",color:"#fff",fontWeight:700}};
export default function AdminChat(){
 const [members,setMembers]=useState([]);const [messages,setMessages]=useState([]);const [text,setText]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);const [notice,setNotice]=useState("");const [notif,setNotif]=useState("default");
 const firstLoad=useRef(true);const seen=useRef({});const selectedRef=useRef("");
 useEffect(()=>{try{if(window.Notification){var p=window.Notification.permission;setNotif(p);if(p==="default")window.Notification.requestPermission().then(setNotif).catch(()=>{});}else setNotif("unsupported")}catch(e){}},[]);
 async function enableNotifications(){try{if(!window.Notification){setNotice("Browser notifications are not supported.");return;}const p=await window.Notification.requestPermission();setNotif(p);if(p==="granted")setNotice("Notifications enabled ✓")}catch(e){setNotice("Could not enable notifications.")}}
 async function loadGroupMessages(){try{const r=await fetch("/api/group-chat");const j=await r.json();if(!r.ok){setError(j.error||"Unable to load group");return;}setMessages(j.messages||[]);setMembers(j.members||[]);}catch(e){setError("Unable to load group messages")}}
 useEffect(()=>{loadGroupMessages();const id=setInterval(loadGroupMessages,2500);return()=>clearInterval(id)},[]);
 async function moderate(phone,action){try{const r=await fetch("/api/group-chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({phone,action})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Action failed");setMembers(ms=>ms.map(x=>x.phone===phone?{...x,chat_blocked:!!j.member.chat_blocked}:x));}catch(e){setError(e.message||"Moderation failed")}}
 async function send(){if(!text.trim()||busy)return;setBusy(true);setError("");try{const r=await fetch("/api/group-chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:text})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Message failed");setText("");setMessages(x=>[...x,j.message]);}catch(e){setError(e.message||"Message failed")}finally{setBusy(false)}}
 return <div style={css.page}><div style={css.top}><b>DESCRIPTIVE MASTER — GROUP CHAT</b><div style={{display:"flex",alignItems:"center",gap:12}}><button onClick={enableNotifications} style={{border:"1px solid rgba(255,255,255,.5)",background:"transparent",color:"#fff",borderRadius:8,padding:"7px 10px",cursor:"pointer",fontSize:12}}>{notif==="granted"?"🔔 Notifications On":"🔔 Enable Notifications"}</button><Link href="/admin" style={{color:"#fff",textDecoration:"none"}}>← Admin Panel</Link></div></div><div style={css.layout}><aside style={css.side}><h3 style={{marginTop:0}}>👥 Student Community</h3><p style={{color:"#667085",fontSize:13}}>Block a student if they misuse the group chat.</p>{members.map(m=><div key={m.phone} style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:6,padding:"9px 0",borderBottom:"1px solid #eef1f5"}}><span><b>{m.name||"Student"}</b><br/><small style={{color:"#667085"}}>{m.phone}</small></span><button onClick={()=>moderate(m.phone,m.chat_blocked?"unblock":"block")} style={{fontSize:11,padding:"5px 8px",borderRadius:7,border:"1px solid #cbd3df",background:m.chat_blocked?"#eefaf2":"#fff4f4",color:m.chat_blocked?"#1b7a4b":"#a52727",cursor:"pointer"}}>{m.chat_blocked?"Unblock":"Block"}</button></div>)}</aside><main style={css.main}>{notice&&<div style={{padding:10,color:"#755b00",background:"#fff8db",border:"1px solid #eee1a6",borderRadius:8,marginBottom:10,fontWeight:700}}>🔔 {notice}</div>}{error&&<div style={{padding:10,color:"#a52727"}}>{error}</div>}<div style={css.card}><div style={{padding:16,borderBottom:"1px solid #e3e7ee",fontWeight:700}}>👥 Student Community <span style={{fontWeight:400,color:"#667085",fontSize:13}}>• All logged-in students</span></div><div style={css.messages}>{messages.length===0?<div style={{textAlign:"center",color:"#667085",paddingTop:80}}>No messages yet.</div>:messages.map(m=><div key={m.id} style={{display:"flex",justifyContent:m.sender==="admin"?"flex-end":"flex-start"}}><div style={{...css.bubble,background:m.sender==="admin"?"#dcecff":"#fff",border:"1px solid #dbe2ec"}}><div style={{fontSize:11,fontWeight:800,color:m.sender==="admin"?"#315d9b":"#56657c",marginBottom:3}}>{m.sender==="admin"?"Admin":(m.name||"Student")}</div><div>{m.message}</div><div style={{fontSize:10,color:"#7a8495",marginTop:4,textAlign:"right"}}>{new Date(m.created_at).toLocaleString("en-IN")}</div></div></div>)}</div><div style={css.composer}><input style={css.input} value={text} onChange={e=>setText(e.target.value.slice(0,2000))} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Message the student group…"/><button style={css.button} disabled={busy} onClick={send}>{busy?"Sending…":"Send"}</button></div></div></main></div></div>;
}
