import {useEffect,useState} from "react";
import Link from "next/link";

const css={page:{minHeight:"100vh",background:"#f5f7fb",fontFamily:"Arial,Helvetica,sans-serif",color:"#172033"},top:{height:64,background:"#40537d",color:"#fff",display:"flex",alignItems:"center",justifyContent:"space-between",padding:"0 20px"},layout:{display:"grid",gridTemplateColumns:"300px 1fr",maxWidth:1200,margin:"0 auto",minHeight:"calc(100vh - 64px)"},side:{background:"#fff",borderRight:"1px solid #d7dee9",padding:16},main:{padding:18},listBtn:{width:"100%",textAlign:"left",background:"#fff",border:"1px solid #d7dee9",borderRadius:10,padding:12,marginBottom:8,cursor:"pointer"},card:{background:"#fff",border:"1px solid #d7dee9",borderRadius:14,overflow:"hidden"},messages:{height:"calc(100vh - 190px)",minHeight:420,overflowY:"auto",padding:18,background:"#f8fafc"},bubble:{maxWidth:"78%",padding:"10px 13px",borderRadius:12,marginBottom:10,lineHeight:1.45,whiteSpace:"pre-wrap"},composer:{display:"flex",gap:10,padding:14,borderTop:"1px solid #e3e7ee"},input:{flex:1,border:"1px solid #cbd3df",borderRadius:10,padding:"11px 13px"},button:{border:0,borderRadius:10,padding:"11px 18px",background:"#3d78c2",color:"#fff",fontWeight:700}};
export default function AdminChat(){
 const [students,setStudents]=useState([]);const [selected,setSelected]=useState("");const [messages,setMessages]=useState([]);const [text,setText]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 async function loadStudents(){try{const r=await fetch("/api/chat");const j=await r.json();if(!r.ok){setError(j.error||"Admin session required");return;}setStudents(j.students||[]);if(!selected&&j.students?.[0])setSelected(j.students[0].phone);}catch(e){setError("Unable to load students")}}
 async function loadMessages(){if(!selected)return;try{const r=await fetch(`/api/chat?phone=${encodeURIComponent(selected)}`);const j=await r.json();if(!r.ok){setError(j.error||"Unable to load messages");return;}setMessages(j.messages||[]);}catch(e){setError("Unable to load messages")}}
 useEffect(()=>{loadStudents();const id=setInterval(loadStudents,5000);return()=>clearInterval(id)},[]);
 useEffect(()=>{loadMessages();const id=setInterval(loadMessages,2500);return()=>clearInterval(id)},[selected]);
 async function send(){if(!text.trim()||!selected||busy)return;setBusy(true);try{const r=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({phone:selected,message:text})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Message failed");setText("");setMessages(x=>[...x,j.message]);}catch(e){setError(e.message||"Message failed")}finally{setBusy(false)}}
 const s=students.find(x=>x.phone===selected);
 return <div style={css.page}><div style={css.top}><b>DESCRIPTIVE MASTER — ADMIN CHAT</b><Link href="/admin" style={{color:"#fff",textDecoration:"none"}}>← Admin Panel</Link></div><div style={css.layout}><aside style={css.side}><h3 style={{marginTop:0}}>Approved Students</h3>{students.length===0?<p style={{color:"#667085",fontSize:13}}>No approved students yet.</p>:students.map(x=><button key={x.phone} style={{...css.listBtn,borderColor:selected===x.phone?"#3d78c2":"#d7dee9",background:selected===x.phone?"#eef5ff":"#fff"}} onClick={()=>setSelected(x.phone)}><b>{x.name||"Student"}</b><div style={{fontSize:12,color:"#667085",marginTop:3}}>{x.phone}</div><div style={{fontSize:11,color:"#7a8495",marginTop:4}}>{x.message_count||0} messages</div></button>)}</aside><main style={css.main}>{error&&<div style={{padding:10,color:"#a52727"}}>{error}</div>}{selected?<div style={css.card}><div style={{padding:16,borderBottom:"1px solid #e3e7ee",fontWeight:700}}>Chat with {s?.name||"Student"} <span style={{fontWeight:400,color:"#667085",fontSize:13}}>• {selected}</span></div><div style={css.messages}>{messages.length===0?<div style={{textAlign:"center",color:"#667085",paddingTop:80}}>No messages yet.</div>:messages.map(m=><div key={m.id} style={{display:"flex",justifyContent:m.sender==="admin"?"flex-end":"flex-start"}}><div style={{...css.bubble,background:m.sender==="admin"?"#dcecff":"#fff",border:"1px solid #dbe2ec"}}><div>{m.message}</div><div style={{fontSize:10,color:"#7a8495",marginTop:4,textAlign:"right"}}>{new Date(m.created_at).toLocaleString("en-IN")}</div></div></div>)}</div><div style={css.composer}><input style={css.input} value={text} onChange={e=>setText(e.target.value.slice(0,2000))} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Reply to student…"/><button style={css.button} disabled={busy} onClick={send}>{busy?"Sending…":"Send"}</button></div></div>:<div style={{...css.card,padding:40,textAlign:"center",color:"#667085"}}>Select a student to open the conversation.</div>}</main></div></div>;
}
