import {useEffect,useRef,useState} from "react";
import Link from "next/link";

const css={page:{minHeight:"100vh",background:"#f5f7fb",fontFamily:"Arial,Helvetica,sans-serif",color:"#172033"},top:{height:64,background:"#40537d",color:"#fff",display:"flex",alignItems:"center",justifyContent:"space-between",padding:"0 20px"},wrap:{maxWidth:850,margin:"0 auto",padding:20},card:{background:"#fff",border:"1px solid #d7dee9",borderRadius:14,overflow:"hidden",boxShadow:"0 5px 20px rgba(25,45,80,.08)"},head:{padding:16,borderBottom:"1px solid #e3e7ee",fontWeight:700},messages:{height:"calc(100vh - 255px)",minHeight:420,overflowY:"auto",padding:18,background:"#f8fafc"},bubble:{maxWidth:"78%",padding:"10px 13px",borderRadius:12,marginBottom:10,lineHeight:1.45,whiteSpace:"pre-wrap"},composer:{display:"flex",gap:10,padding:14,borderTop:"1px solid #e3e7ee"},input:{flex:1,border:"1px solid #cbd3df",borderRadius:10,padding:"11px 13px",outline:"none"},button:{border:0,borderRadius:10,padding:"11px 18px",background:"#3d78c2",color:"#fff",fontWeight:700}};

export default function Chat(){
 const [phone,setPhone]=useState("");const [name,setName]=useState("Student");const [messages,setMessages]=useState([]);const [text,setText]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);const bottom=useRef(null);
 useEffect(()=>{const p=(localStorage.getItem("dm_phone")||"").replace(/\D/g,"");setPhone(p);setName(localStorage.getItem("dm_name")||"Student");if(!p)window.location.href="/";},[]);
 async function load(){if(phone.length!==10)return;try{const r=await fetch(`/api/chat?phone=${encodeURIComponent(phone)}`);const j=await r.json();if(!r.ok){setError(j.error||"Unable to load chat");return;}setMessages(j.messages||[]);}catch(e){setError("Unable to connect to chat");}}
 useEffect(()=>{load();const id=setInterval(load,2500);return()=>clearInterval(id)},[phone]);
 useEffect(()=>bottom.current?.scrollIntoView({behavior:"smooth"}),[messages]);
 async function send(){if(!text.trim()||busy)return;setBusy(true);setError("");try{const r=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({phone,message:text})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Message failed");setText("");setMessages(x=>[...x,j.message]);}catch(e){setError(e.message||"Message failed")}finally{setBusy(false)}}
 return <div style={css.page}><div style={css.top}><b>DESCRIPTIVE MASTER</b><Link href="/" style={{color:"#fff",textDecoration:"none"}}>← Dashboard</Link></div><div style={css.wrap}><div style={css.card}><div style={css.head}>Chat with Admin <span style={{fontWeight:400,color:"#667085",fontSize:13}}>• {name}</span></div><div style={css.messages}>{messages.length===0?<div style={{color:"#667085",textAlign:"center",paddingTop:80}}>No messages yet. Send a message to contact the admin.</div>:messages.map(m=><div key={m.id} style={{display:"flex",justifyContent:m.sender==="student"?"flex-end":"flex-start"}}><div style={{...css.bubble,background:m.sender==="student"?"#dcecff":"#fff",border:"1px solid #dbe2ec"}}><div>{m.message}</div><div style={{fontSize:10,color:"#7a8495",marginTop:4,textAlign:"right"}}>{new Date(m.created_at).toLocaleString("en-IN")}</div></div></div>)}<div ref={bottom}/></div>{error&&<div style={{padding:"10px 14px",color:"#a52727",fontSize:13}}>{error}</div>}<div style={css.composer}><input style={css.input} value={text} onChange={e=>setText(e.target.value.slice(0,2000))} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Type your message…"/><button style={css.button} disabled={busy} onClick={send}>{busy?"Sending…":"Send"}</button></div></div></div></div>;
}
